fix(cli): set error code when calling CLI with bad command

diff --git a/test/integ/run b/test/integ/run
--- a/test/integ/run
+++ b/test/integ/run
@@ -8,6 +8,17 @@ cd ${garden_root}/examples/hello-world
 
 export GARDEN_LOGGER_TYPE=basic
 
+# make sure CLI returns with error when it should
+set +e
+
+${garden_bin} bla
+if [[ $? -eq 0 ]]; then
+  echo "Expected error when calling with bad command"
+  exit 1
+fi
+
+set -e
+
 ${garden_bin} scan
 ${garden_bin} build
 ${garden_bin} deploy
