chore: maybe fail now?

diff --git a/.github/workflows/reusable-create-homebrew-pr.yml b/.github/workflows/reusable-create-homebrew-pr.yml
--- a/.github/workflows/reusable-create-homebrew-pr.yml
+++ b/.github/workflows/reusable-create-homebrew-pr.yml
@@ -35,12 +35,12 @@ jobs:
         id: fetch-arm-sha256
         if: inputs.release-condition != 'false'
         run: |
-          echo "sha256=$(curl -sSL --fail ${{ env.ARM_TARBALL_URL }} | shasum -a 256 | cut -d ' ' -f 1)" >> "$GITHUB_OUTPUT"
+          echo "sha256=$(set -o pipefail && curl -sSL --fail ${{ env.ARM_TARBALL_URL }}/fail | shasum -a 256 | cut -d ' ' -f 1)" >> "$GITHUB_OUTPUT"
       - name: Fetch amd sha256
         id: fetch-amd-sha256
         if: inputs.release-condition != 'false'
         run: |
-          echo "sha256=$(curl -sSL --fail ${{ env.AMD_TARBALL_URL }} | shasum -a 256 | cut -d ' ' -f 1)" >> "$GITHUB_OUTPUT"
+          echo "sha256=$(set -o pipefail && curl -sSL --fail ${{ env.AMD_TARBALL_URL }} | shasum -a 256 | cut -d ' ' -f 1)" >> "$GITHUB_OUTPUT"
 
   homebrew-create-pr:
     runs-on: ubuntu-latest
